export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_TODOITEM = 'add_todoItem'
export const DELETE_TODOITEM = 'delete_todoItem'
export const INIT_LIST_ACTION = 'init_list_action'
export const GET_INIT_LIST_SAGA = 'get_init_list_saga'
